### ISSUE TITLE
secret notes todo

### ISSUE THREAD

**Issue by AlexChien** [bitsuperlab/web_play#33]
- [ ] disable/hint un-registered books
- [ ] new created account not displayed in dropdown menu
- [ ] sort notes by timestamp desc
- [ ] pagination
- [ ] separate create form

**Comment by AlexChien** [comment]
progress:
288a3fdeab (move compose note to dialog)
d78fd81490 (note default type secret_type)
e7352a04df (my winning records)
cdd600b975 (api update: list_operation_reward_transactions)
a61a796e08 (better balance tip and place it right under amount input)
...
